Airbnb Short-term Rentals

1. What is the most common room type in NYC Airbnb listings?
SELECT room_type, COUNT(room_type) room_type_count
FROM room_types
GROUP BY room_type
ORDER BY room_type_count
LIMIT 1;

entire home/apt = 13266

2. What is the average price of a listing by room type? shared room
SELECT room_type, AVG(price) avg_price
FROM room_types rt
LEFT JOIN prices p
ON rt.listing_id = p.listing_id
GROUP BY room_type

53.65

3. Which borough has the highest average price per month?

SELECT borough, AVG(price_per_month) avg_price_per_month
FROM prices 
GROUP BY borough
ORDER BY avg_price_per_month DESC
LIMIT 1;

Manhattan = 5596.68729411022

4. How many listings of each room type are in each borough?
SELECT borough, room_type, COUNT(room_type) room_type_count
FROM prices p
RIGHT JOIN room_types rt
ON rt.listing_id = p.listing_id
GROUP BY borough, room_type
ORDER BY borough

Staten Island, shared room = 2

5. How many listings in each room type category have a price of over $500 per night? private room

WITH room_prices AS (
    SELECT room_type, price
    FROM prices p
    RIGHT JOIN room_types rt
    ON rt.listing_id = p.listing_id
    WHERE price > 500)
SELECT room_type, COUNT(room_type) room_type_count
FROM room_prices
GROUP BY room_type   

19

6. What is the distribution of listing prices by borough?

SELECT borough, MAX(price), MIN(price), AVG(price)
FROM prices
GROUP BY borough;

Queens, max = 2600

7. What is the estimated amount of revenue generated by hosts in each borough?
SELECT borough, 
SUM(price * booked_days_365) rev_per_host
FROM prices p
RIGHT JOIN reviews r
ON r.listing_id = p.listing_id
GROUP BY borough

Queen's = 58404083


8. What is the average price per month for listings in each neighborhood?
SELECT neighbourhood, room_type, AVG(price_per_month)
FROM prices p
RIGHT JOIN room_types rt
ON rt.listing_id = p.listing_id
GROUP BY neighbourhood, room_type
ORDER BY neighbourhood;

Sea Gate, entire home/apt = 24485.4166665


9. How many listings have no reviews?
SELECT COUNT(last_review)
FROM reviews
WHERE number_of_reviews = 0 OR number_of_reviews ISNULL;

0

10. How do the estimated book days correlate with the price of an Airbnb listing in New York City?
SELECT CORR(booked_days_365, price) corr_booked_days_price
FROM reviews r
LEFT JOIN prices p
ON r.listing_id = p.listing_id

-0.07963883976667008

